//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dem.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routes()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int RouteID { get; set; }
        public string RouteNumber { get; set; }
        public int DepartureCityID { get; set; }
        public int ArrivalCityID { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public int BusID { get; set; }
        public int DriverID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public decimal Price { get; set; }
        public int FreeSeats { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Cities Cities1 { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Platforms Platforms { get; set; }
        public virtual RouteStatuses RouteStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
