//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dem.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int TicketID { get; set; }
        public int RouteID { get; set; }
        public int PassengerID { get; set; }
        public Nullable<int> CashierID { get; set; }
        public int SeatNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDateTime { get; set; }
        public string Status { get; set; }
    
        public virtual Cashiers Cashiers { get; set; }
        public virtual Passengers Passengers { get; set; }
        public virtual Routes Routes { get; set; }
    }
}
